export const SET_CARDS = "SET_CARDS";
export const GET_CARDS = "GET_CARDS";
export const GET_CARDS_BY_ID = "GET_CARDS_BY_ID";
export const GET_CARDS_BY_NAME = "GET_CARDS_BY_NAME";
export const SET_CARDS_LOADING = "SET_CARDS_LOADING";
export const SET_MYCARDS = "SET_MYCARDS";
export const REMOVE_MYCARDS_BY_ID = "REMOVE_MYCARDS_BY_ID";